apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: telegram-operator
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]

  - apiGroups: ["telegram.alert"]
    resources: ["telegramnotifiers"]
    verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: telegram-operator-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: telegram-operator
subjects:
  - kind: ServiceAccount
    name: telegram-operator
    namespace: default

