apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: telegramnotifiers.telegram.alert
spec:
  group: telegram.alert
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                botToken:
                  type: string
                chatID:
                  type: string
                events:
                  type: array
                  items:
                    type: string
                namespaces:
                  type: array
                  items:
                    type: string
  scope: Cluster
  names:
    plural: telegramnotifiers
    singular: telegramnotifier
    kind: TelegramNotifier
    shortNames:
      - telnot

